# Site settings
title: Wmitrut's Blog
email: your-email@domain.com
description: "Blog and site about Wmitrut, discovering Ruby on Rails, software development, project management, technology in general and lifestyle"
baseurl: ""
url: "http://wmitrut.github.io"

# Build settings
markdown: kramdown
permalink: pretty
