# Site settings
title: Wellington Mitrut
header-img: img/share.png
email: wellingtonmitrut@gmail.com
description: "Hi, I'm Wellington Mitrut, a Designer/Developer from Brazil. I worked with many startups, open-source projects and now I'm Mobile Advocate at Tampa.Works, conference speaker and open source enthusiastic."
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: "wmitrut.pro"
twitter_username: Wmitrut
github_username:  wmitrut
facebook_username:  wmitrut
soundcloud_username:  wmitrut
youtube_channel:  wmitrut
medium_username:  wmitrut

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate]